language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit